server:
  port: 8080
  servlet:
    session:
      timeout: 1800 # 로그인 세션 유지시간 30분
      tracking-modes: cookie

spring:
  #datasource:
    #url: jdbc:mysql://localhost:3306/tcudb?serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8
    #username: root
    #password: password
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:h2:tcp://localhost/~/tcu
    #username: sa
    #password:
    #driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    dirver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test


  jpa:
    hibernate:
      ddl-auto: create
      #ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
        #dialect: org.hibernate.dialect.MySQL5InnoDBDialect

logging.level:
  org.hibernate.SQL: debug
  #org.apache.coyote.http11: debug # http 요청 메시지 보기

jwt:
  privateKey: I want to love. but lt is so difficult..

spring.servlet.multipart.maxFileSize: 10MB
spring.servlet.multipart.maxRequestSize: 10MB

store.path:
  #image: /Users/hongseungtaeg/Desktop/toyproject/toyProject4-Monolithic web/onchall/src/main/resources/static/image/
  #file: /Users/hongseungtaeg/Desktop/toyproject/toyProject4-Monolithic web/onchall/src/main/resources/static/file/
  image: C:\Users\s_gmtmoney2357\Desktop\ToyProject\ToyProject4\onchall\src\main\resources\static\image\
  file: C:\Users\s_gmtmoney2357\Desktop\ToyProject\ToyProject4\onchall\src\main\resources\static\file\